version: 2
updates:
  # Enable version updates for npm/pnpm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check for updates once a week
    schedule:
      interval: 'weekly'
    # Allow up to 10 open pull requests for dependencies
    open-pull-requests-limit: 10
    # Assign pull requests to specific reviewers
    assignees:
      - 'sivakumar00'
    # Labels on pull requests for npm dependencies
    labels:
      - 'dependencies'
      - 'pnpm'
    # Set the versioning strategy
    versioning-strategy: auto
    # Use pnpm as the package manager
    package-manager: 'pnpm'
    # Ignore certain dependencies
    ignore:
      # Ignore major version updates for these packages
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']

  # Check packages in core directory
  - package-ecosystem: 'npm'
    directory: '/packages/core'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    assignees:
      - 'sivakumar00'
    labels:
      - 'dependencies'
      - 'core'
    package-manager: 'pnpm'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    assignees:
      - 'sivakumar00'
    labels:
      - 'github-actions'
      - 'dependencies'
